"""Add SharedReport model

Revision ID: 7039e8323eca
Revises: 
Create Date: 2025-05-06 11:27:03.351538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7039e8323eca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=100), nullable=False),
    sa.Column('report_title', sa.String(length=100), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_report')
    # ### end Alembic commands ###
